<a href="https://colab.research.google.com/github/chandra0013/py/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
print('About Data Science Tools')
#Slicing
match='lol lmao'
print(match[:4])
mat=match.split()
print(mat)
print(mat[0])

About Data Science Tools
lol
['lol', 'lmao']
lol

In [77]:
s="vit-workshop-on-data-science"
print(s[16:20])
lol=s.split("-")[3]
print(lol)

data
data

In [78]:
#dictionary
student={'regno':101,'name':'kiran reddy','branch':'cse','cgpa':9.5}
fus=student['name'].split()
print(fus[1])

reddy

In [79]:
marks=[20,3,23,233]
print(marks)
print(type(marks))
print(marks[1:4:2])

[20, 3, 23, 233]
<class 'list'>
[3, 233]

In [80]:
#to check if a number is prime or composite
n=int(input("enter the number"))
for i in range(2,n):
  if n%i==0:
     print("composite")
     break
else:
  print("Prime")

enter the number5
Prime

In [81]:
l1=[1,2,3,4,5,6]
l2=[12,13,45,6,73,122]
print(list(zip(l1,l2)))
for i,j in zip(l1,l2):
  print(i+j)

[(1, 12), (2, 13), (3, 45), (4, 6), (5, 73), (6, 122)]
13
15
48
10
78
128

In [82]:
import pandas as pd
cars=pd.read_csv('/content/cars_data.csv')
cars

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [83]:
cars.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

# 1 Pre-Processing
Handling the null valuEs
Remove the invalid data
Remove the outliners
Transform the data to the required

In [84]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6017 non-null   object
 8   Engine             5983 non-null   object
 9   Power              5983 non-null   object
 10  Seats              5977 non-null   float64
 11  New_Price          824 non-null    object
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 611.4+ KB

In [85]:
# cars=cars.drop('New_Price',axis=1)
cars.isnull().sum()
#axis is equal to 1 cuz we are removing column if we have to remove a row axis =0

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [86]:
cars['Mileage']=cars['Mileage'].str.split().str[0]
cars['Mileage']

0        26.6
1       19.67
2        18.2
3       20.77
4        15.2
        ...
6014     28.4
6015     24.4
6016     14.0
6017     18.9
6018    25.44
Name: Mileage, Length: 6019, dtype: object

In [87]:
cars['Mileage']=pd.to_numeric(cars['Mileage'])

In [88]:
 cars['Mileage'].mean()

18.134960943992024

In [89]:
cars['Mileage']=cars['Mileage'].fillna(round(cars['Mileage'].mean(),2))
cars['Mileage']

0       26.60
1       19.67
2       18.20
3       20.77
4       15.20
        ...
6014    28.40
6015    24.40
6016    14.00
6017    18.90
6018    25.44
Name: Mileage, Length: 6019, dtype: float64

In [90]:
cars['Seats']=cars['Seats'].fillna(round(cars['Seats'].mean(),2))
cars['Seats']

0       5.0
1       5.0
2       5.0
3       7.0
4       5.0
       ...
6014    5.0
6015    5.0
6016    8.0
6017    5.0
6018    5.0
Name: Seats, Length: 6019, dtype: float64

In [91]:
cars['Engine']=cars['Engine'].str.split().str[0]
cars['Engine']

0        998
1       1582
2       1199
3       1248
4       1968
        ...
6014    1248
6015    1120
6016    2498
6017     998
6018     936
Name: Engine, Length: 6019, dtype: object

In [92]:
cars['Engine']=pd.to_numeric(cars['Engine'])

In [93]:
cars['Engine']=cars['Engine'].fillna(round(cars['Engine'].mean(),2))
cars['Engine']

0        998.0
1       1582.0
2       1199.0
3       1248.0
4       1968.0
         ...
6014    1248.0
6015    1120.0
6016    2498.0
6017     998.0
6018     936.0
Name: Engine, Length: 6019, dtype: float64

In [94]:
cars['Power']=cars['Power'].str.split().str[0]
cars['Power']

0       58.16
1       126.2
2        88.7
3       88.76
4       140.8
        ...
6014       74
6015       71
6016      112
6017     67.1
6018     57.6
Name: Power, Length: 6019, dtype: object

In [95]:
cars['Power']=pd.to_numeric(cars['Power'])

ValueError: ignored

In [96]:
cars[cars['Power']=='null']

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
76,Ford Fiesta 1.4 SXi TDCi,Jaipur,2008,111111,Diesel,Manual,First,17.80,1399.0,null,5.00,NaN,2.00
79,Hyundai Santro Xing XL,Hyderabad,2005,87591,Petrol,Manual,First,0.00,1086.0,null,5.00,NaN,1.30
89,Hyundai Santro Xing XO,Hyderabad,2007,73745,Petrol,Manual,First,17.00,1086.0,null,5.00,NaN,2.10
120,Hyundai Santro Xing XL eRLX Euro III,Mumbai,2005,102000,Petrol,Manual,Second,17.00,1086.0,null,5.00,NaN,0.85
143,Hyundai Santro Xing XO eRLX Euro II,Kochi,2008,80759,Petrol,Manual,Third,17.00,1086.0,null,5.00,NaN,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873,Hyundai Santro Xing XO eRLX Euro II,Pune,2006,47200,Petrol,Manual,Second,17.00,1086.0,null,5.00,NaN,1.20
5893,Maruti Estilo LXI,Chennai,2008,51000,Petrol,Manual,Second,19.50,1061.0,null,5.28,NaN,1.75
5925,Skoda Laura Classic 1.8 TSI,Pune,2010,85000,Petrol,Manual,First,17.50,1798.0,null,5.00,NaN,2.85
5943,Mahindra Jeep MM 540 DP,Chennai,2002,75000,Diesel,Manual,First,0.00,2112.0,null,6.00,NaN,1.70
5985,Toyota Etios GD,Delhi,2013,70000,Diesel,Manual,First,23.59,1364.0,null,5.00,NaN,3.88

In [99]:
cars['Power']=cars['Power'].replace('null',0)
cars['Power']

0       58.16
1       126.2
2        88.7
3       88.76
4       140.8
        ...
6014       74
6015       71
6016      112
6017     67.1
6018     57.6
Name: Power, Length: 6019, dtype: object

In [100]:
cars['Power']=pd.to_numeric(cars['Power'])

In [101]:
cars['Power']=cars['Power'].fillna(round(cars['Power'].mean(),2))
cars['Power']

0        58.16
1       126.20
2        88.70
3        88.76
4       140.80
         ...
6014     74.00
6015     71.00
6016    112.00
6017     67.10
6018     57.60
Name: Power, Length: 6019, dtype: float64

In [106]:
cars.info()
numeric_columns=cars.select_dtypes(['float64','int64']).columns
for col in numeric_columns:
  print(col,len(cars[cars[col]==0]))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6019 non-null   float64
 8   Engine             6019 non-null   float64
 9   Power              6019 non-null   float64
 10  Seats              6019 non-null   float64
 11  New_Price          824 non-null    object
 12  Price              6019 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 611.4+ KB
Year 0
Kilometers_Driven 0
Mileage 68
Engine 0
Power 107
Seats 1
Price 0

In [109]:
cars[cars['Seats']==0]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
3999,Audi A4 3.2 FSI Tiptronic Quattro,Hyderabad,2012,125000,Petrol,Automatic,First,10.5,3197.0,0.0,0.0,NaN,18.0

In [114]:
numeric_columns=cars.select_dtypes(['float64','int64']).columns
for col in numeric_columns:
  cars[col]=cars[col].replace(0,cars[col].mean())
  cars[col]
for col in numeric_columns:
 print(col,len(cars[cars[col]==0]))

Year 0
Kilometers_Driven 0
Mileage 0
Engine 0
Power 0
Seats 0
Price 0

In [117]:
cars['Year']==2010
cars[cars['Year']==2019]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
67,Mercedes-Benz C-Class Progressive C 220d,Coimbatore,2019,15369,Diesel,Automatic,First,18.134959,1950.0,194.00,5.0,49.14 Lakh,35.67
135,Hyundai Verna VTVT 1.6 AT SX Plus,Kochi,2019,12645,Petrol,Automatic,First,17.000000,1591.0,121.30,5.0,13.49 Lakh,11.50
155,Hyundai EON Magna Plus,Kochi,2019,14322,Petrol,Manual,First,21.100000,814.0,55.20,5.0,NaN,4.23
173,Hyundai Grand i10 1.2 Kappa Asta,Kolkata,2019,1000,Petrol,Manual,First,18.900000,1197.0,81.86,5.0,7.39 Lakh,6.50
235,Toyota Innova Crysta 2.8 GX AT,Kochi,2019,14165,Diesel,Automatic,First,11.360000,2755.0,171.50,7.0,20.74 Lakh,19.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5769,Tata Tiago 1.2 Revotron XZ,Coimbatore,2019,20712,Petrol,Manual,First,23.840000,1199.0,84.00,5.0,6.59 Lakh,6.94
5789,Renault KWID RXL,Kochi,2019,7858,Petrol,Manual,First,25.170000,799.0,53.30,5.0,4.04 Lakh,3.80
5805,Skoda Rapid 1.6 MPI Ambition,Coimbatore,2019,21214,Petrol,Manual,First,15.410000,1598.0,103.52,5.0,12.44 Lakh,9.66
5860,Mahindra Thar CRDe AC,Coimbatore,2019,16392,Diesel,Manual,First,16.550000,2498.0,105.00,6.0,NaN,10.36
5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,4000,Diesel,Automatic,First,18.134959,1950.0,194.00,5.0,49.14 Lakh,35.00

In [118]:
import plotly.express as px
px.box(data_frame=cars,x='Mileage')

In [119]:
cars['Mileage']>33

0       False
1       False
2       False
3       False
4       False
        ...
6014    False
6015    False
6016    False
6017    False
6018    False
Name: Mileage, Length: 6019, dtype: bool

In [120]:
cars[cars['Mileage']>33].index

Int64Index([1269, 1332, 2059, 2371, 3129, 3553, 3869, 4141, 4769], dtype='int64')

In [121]:
cars=cars.drop(cars[cars['Mileage']>33].index)

In [123]:
cars['Fuel_Type'].value_counts()

Diesel      3205
Petrol      2746
CNG           47
LPG           10
Electric       2
Name: Fuel_Type, dtype: int64

In [126]:
ft_old=cars['Fuel_Type'].value_counts().index
ft_new=list(range(len(cars['Fuel_Type'].value_counts().index)))
print(ft_old)
print(ft_new)

Index(['Diesel', 'Petrol', 'CNG', 'LPG', 'Electric'], dtype='object')
[0, 1, 2, 3, 4]

In [127]:
cars['Fuel_Type']=cars['Fuel_Type'].replace(ft_old,ft_new)

In [130]:
loc_old=cars['Location'].value_counts().index
loc_new=list(range(len(cars['Location'].value_counts().index)))
cars['Location']=cars['Location'].replace(loc_old,loc_new)

In [131]:
tra_old=cars['Transmission'].value_counts().index
tra_new=list(range(len(cars['Transmission'].value_counts().index)))
cars['Transmission']=cars['Transmission'].replace(tra_old,tra_new)

In [132]:
ot_old=cars['Owner_Type'].value_counts().index
ot_new=list(range(len(cars['Owner_Type'].value_counts().index)))
cars['Owner_Type']=cars['Owner_Type'].replace(ot_old,ot_new)

In [134]:
cars['Brands']=cars['Name'].str.split().str[0]
cars['Brands']

0          Maruti
1         Hyundai
2           Honda
3          Maruti
4            Audi
          ...
6014       Maruti
6015      Hyundai
6016     Mahindra
6017       Maruti
6018    Chevrolet
Name: Brands, Length: 6010, dtype: object

In [135]:
cars['Model']=cars['Name'].str.split().str[1]
cars['Model']
cars=cars.drop('Name',axis=1)

In [137]:
br_old=cars['Brands'].value_counts().index
br_new=list(range(len(cars['Brands'].value_counts().index)))
cars['Brands']=cars['Brands'].replace(br_old,br_new)

In [138]:
cars['Brands']

0        0
1        1
2        2
3        0
4        9
        ..
6014     0
6015     1
6016     7
6017     0
6018    13
Name: Brands, Length: 6010, dtype: int64

In [139]:
cars

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brands,Model
0,0,2010,72000,2,0,0,26.60,998.0,58.16,5.0,NaN,1.75,0,Wagon
1,4,2015,41000,0,0,0,19.67,1582.0,126.20,5.0,NaN,12.50,1,Creta
2,7,2011,46000,1,0,0,18.20,1199.0,88.70,5.0,8.61 Lakh,4.50,2,Jazz
3,7,2012,87000,0,0,0,20.77,1248.0,88.76,7.0,NaN,6.00,0,Ertiga
4,3,2013,40670,0,1,1,15.20,1968.0,140.80,5.0,NaN,17.74,9,A4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,5,2014,27365,0,0,0,28.40,1248.0,74.00,5.0,7.88 Lakh,4.75,0,Swift
6015,8,2015,100000,0,0,0,24.40,1120.0,71.00,5.0,NaN,4.00,1,Xcent
6016,8,2012,55000,0,0,1,14.00,2498.0,112.00,8.0,NaN,2.90,7,Xylo
6017,6,2013,46000,1,0,0,18.90,998.0,67.10,5.0,NaN,2.65,0,Wagon
6018,1,2011,47000,0,0,0,25.44,936.0,57.60,5.0,NaN,2.50,13,Beat

In [140]:
cars.corr()

<ipython-input-140-9ac39f643503>:1: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brands
Location,1.000000,-0.126321,0.053101,-0.060299,-0.081161,0.131721,0.039626,-0.026228,-0.046885,0.000100,-0.067048,-0.027028
Year,-0.126321,1.000000,-0.172865,-0.122101,0.097433,-0.397058,0.292506,-0.051119,0.015910,0.012512,0.305756,0.002066
Kilometers_Driven,0.053101,-0.172865,1.000000,-0.098840,-0.025817,0.085246,-0.064088,0.090823,0.032976,0.083901,-0.011617,0.023052
Fuel_Type,-0.060299,-0.122101,-0.098840,1.000000,-0.143288,0.043310,-0.090407,-0.422601,-0.292983,-0.295179,-0.313407,-0.279383
Transmission,-0.081161,0.097433,-0.025817,-0.143288,1.000000,-0.008993,-0.358931,0.498643,0.638930,-0.074739,0.585805,0.279197
Owner_Type,0.131721,-0.397058,0.085246,0.043310,-0.008993,1.000000,-0.150983,0.050238,0.024398,0.013482,-0.097755,0.036530
Mileage,0.039626,0.292506,-0.064088,-0.090407,-0.358931,-0.150983,1.000000,-0.640477,-0.548418,-0.344395,-0.330285,-0.253634
Engine,-0.026228,-0.051119,0.090823,-0.422601,0.498643,0.050238,-0.640477,1.000000,0.858993,0.396388,0.656976,0.363796
Power,-0.046885,0.015910,0.032976,-0.292983,0.638930,0.024398,-0.548418,0.858993,1.000000,0.099221,0.767705,0.366839
Seats,0.000100,0.012512,0.083901,-0.295179,-0.074739,0.013482,-0.344395,0.396388,0.099221,1.000000,0.052423,0.017876
Price,-0.067048,0.305756,-0.011617,-0.313407,0.585805,-0.097755,-0.330285,0.656976,0.767705,0.052423,1.000000,0.328223
Brands,-0.027028,0.002066,0.023052,-0.279383,0.279197,0.036530,-0.253634,0.363796,0.366839,0.017876,0.328223,1.000000

In [141]:
cars.corr()['Price']

<ipython-input-141-10f60c1c8701>:1: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.

Location            -0.067048
Year                 0.305756
Kilometers_Driven   -0.011617
Fuel_Type           -0.313407
Transmission         0.585805
Owner_Type          -0.097755
Mileage             -0.330285
Engine               0.656976
Power                0.767705
Seats                0.052423
Price                1.000000
Brands               0.328223
Name: Price, dtype: float64

In [142]:
#linear regression
#y=mx+c(Best Fit line)(this is just for one relation for suppose year and price)
#Actual formula is y=m1x1+m2x2+......+mnxn+C,where C is equal to c1+c2+....+cn
X=cars.drop('Price',axis=1)
y=cars['Price']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [143]:
X_train.shape

(4507, 13)

In [144]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
#lr.coef_ gives output of m1,m2,m3,m4.....
#lr.intercept gives C

In [148]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [152]:
dtr.fit(X_train,y_train)

ValueError: ignored